version: '3.9'
services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test

